name: dispatch update file
on:
  pull_request:
    types: [closed]
    paths:
      - "composables/**"
jobs:
  dispatch-target-updated:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        repo: ["wattanx/repository-dispatch-target"]
    name: dispatch-target-updated
    runs-on: ubuntu-latest
    steps:
      - name: dispatch target-updated
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: target-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.event.pull_request.head.sha }}", "url": "${{ github.event.pull_request.html_url }}"}'
